### ISSUE TITLE
Getting erros when trying to start

### ISSUE THREAD

**Issue by Rafficer** [Slethen/ProtonVPN-Gtk#17]
Freshly cloned repo

Running `sudo python ProtonVPN.py`

and getting the following output:

```
➜  ProtonVPN-Gtk git:(master) sudo python ProtonVPN.py
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
[1]    2021 segmentation fault  sudo python ProtonVPN.py
```

Reboot didn't help either... Not sure what's going on.

**Comment by joelbduncan** [comment]
Now that is interesting.

Looks like a CLi issue maybe.

Does this happen as soon as you open the app?
And does the GTK interface load? Also what distro are you using? And python version?

There is a new dependency python-schedule.

**Comment by Rafficer** [comment]
CLI works. Yes, happens as soon as I try to start it, GUI isn't loaded at that point.

The gui crashed for some reason the first time and I couldn't solve it, so I tried a reboot... wondering why that didn't help though...

Distro: Ubuntu 17.10

```
➜  ~ python --version
Python 2.7.14
```

schedule is installed.

```
➜  ~ pip install schedule
Collecting schedule
  Using cached schedule-0.5.0-py2.py3-none-any.whl
Installing collected packages: schedule
Successfully installed schedule-0.5.0
```

**Comment by joelbduncan** [comment]
Thanks a lot for the extra info.
I'm guessing you're using GNOME?

Do you might putting this in ProtonVPN-Gtk folder and running it **without** sudo and let me know the result. It looks like the problem could be to do with XServer/Wayland. Please let me know if you're using Wayland as this has issues with running applications as root.

[ProtonVPN-No-Root.zip](https://github.com/Slethen/ProtonVPN-Gtk/files/1868567/ProtonVPN-No-Root.zip)

Also if you're using Wayland could you change to XServer on GNOME Login screen then running the app as root from master branch.

**Comment by Rafficer** [comment]
Wayland was the problem. It just works with Xorg... Thanks a lot!

**Comment by joelbduncan** [comment]
No problem! Thanks for the feedback I'll add Wayland compatibility to the README.
