### ISSUE TITLE
Connection Status Not Constant

### ISSUE THREAD

**Issue by MitchellRandom** [Slethen/ProtonVPN-Gtk#4]
Just noticed the Status message is not remaining consistent while a connection is active.

It can be observed that the status will change from Connected to Disconnected and back to Connected on the GUI, from what I can tell the actual VPN connection remains.

Issue seems to be based solely on the GUI rather than any issues with the VPN.

**Comment by joelbduncan** [comment]
That's interesting I'm not experiencing this.
Could be the remote API is being requested too many times.

How often is the message changing?

**Comment by joelbduncan** [comment]
My bad I was talking about the location/IP Address section.

I've tried to repeat this but to no avail, I'm pretty sure its unrelated to the VPN as you say.

I'm not happy with how I detect the connection status I may look into an alternative method.

**Comment by MitchellRandom** [comment]
I can no longer replicate this. Tested on connections to SE#8 and SG#3
