### ISSUE TITLE
Redundant Code in GUI Components

### ISSUE THREAD

**Issue by MitchellRandom** [Slethen/ProtonVPN-Gtk#5]
Correct me if I am wrong, but it seems like the following code is not of any use. Tested a build without them and everything seemed to run smooth.

`self.usernameInput = builder.get_object('usernameInput')
self.passwordInput = builder.get_object('passwordInput')`

**Comment by joelbduncan** [comment]
That's correct! That's legacy code from when I used OpenVPN config files instead of protonvpn-cli. I'll remove this when I'm home

**Comment by joelbduncan** [comment]
Resolved in d9f93ee2a3be3ff284601f72bf5d1285310c494b
