### ISSUE TITLE
High CPU Usage & Frequent Unrecoverable Freezes

### ISSUE THREAD

**Issue by joelbduncan** [Slethen/ProtonVPN-Gtk#9]
I've been experiencing frequent crashes that I believe are due to the way I've used threads.

I've exhausted methods I've found in GNOME documentation for threading no matter what I try
I get the same issue that is repeatable every time I use the app for long periods of time.
Or minimize it for short amounts of time.

![protonvpn-gtk-crash](https://user-images.githubusercontent.com/1405445/38161857-57976460-34ce-11e8-88f3-ec5a026e04b3.png)

When using GDB you can see that the applications is still running the threaded side of the application
just the GTK GUI seems to freeze.

**Comment by MitchellRandom** [comment]
Interesting, I have been experiencing high CPU usage too. Initially, I put it down to building the brave-browser. However, perhaps the GUI has resulted in this.

It must be noted that the GUI, during my period of high load, enables a brief period of functionality then it begins to fail responding.

Once I complete my build of brave-browser I can get confirmation on whether my experience is due to the python

**Comment by joelbduncan** [comment]
Do update me if you conclude you are experiencing a similar issue.

I believe I've traced the problem but I don't think it's easy to solve.
When using GDB you can see it's creating a new thread before finishing the network/socket request used for IP, Location & Connection status.

I'm looking into Thread safety in Python/Gdk but not having a lot of luck.

**Comment by MitchellRandom** [comment]
I restarted my system earlier today and that cleared up my high CPU usage. At the moment the program is running smoothly.

However, I will keep an eye on how it performs as time goes on.

**Comment by MitchellRandom** [comment]
Update: Seems that after having the GUI minimised for a while it becomes unresponsive when attempting to maximise again.

**Comment by MitchellRandom** [comment]
I have experienced a number of crashes which I believe is linked to the threading.
![image](https://user-images.githubusercontent.com/20890187/38173979-159a63c8-35be-11e8-9b94-9e111846717a.png)

![image](https://user-images.githubusercontent.com/20890187/38173985-22db8df0-35be-11e8-975d-0920fbc0aead.png)

![image](https://user-images.githubusercontent.com/20890187/38174000-40ceaafe-35be-11e8-9e22-281b4304377b.png)

![image](https://user-images.githubusercontent.com/20890187/38174017-640c1416-35be-11e8-92dd-c55be24bfdcf.png)

**Comment by joelbduncan** [comment]
The Allocating size to GtkWindow is a bug in GTK 3.20/3.22 apparently.
This can be fixed by setting a fixed size to all Gtk grids that get resized when the UI updates.

The segmentation fault is likely the threading I've also experienced this.

I've stripped down the code and been experimenting with alternative methods:

Gio
Python async call
Python-Schedule

No luck yet unfortunately.

**Comment by MitchellRandom** [comment]
Ah yeah apologies. Only included the Allocating size messages to give the segmentation fault and invalid pointer fault a bit more body for the screenshots.
